### ISSUE TITLE
admin 账户用户管理页面增加搜索功能

### ISSUE THREAD

**Issue by breakwang** [bsc-s2/storage-dashboard-vue#1]
现在页面只有一个搜索框，我试了下，感觉应该是针对username 和 email 搜索的

提一些小改进意见
1. 展示用户信息中 增加公司名，账户使用的存储容量。
2. 增加对其他字段的搜索功能（公司名，创建时间（范围搜索），容量（范围筛选））
3.  可以根据用户创建时间和容量大小进行排序显示 
4. 默认创建的用户和管理员账户绑定（这块我不太了解为啥需要手动挷一次）

目标是实现一个管理员能够从页面上获取一些统计信息

**Comment by drmingdrmer** [comment]
> 增加一个账号类型吧 admin_high admin_low
high 和 low分别都是什么设定额?

**Comment by chenanyuan** [comment]
admin_high    默认关联所有存储账号
admin_low      售前关联自己的客户的存储账号
本来的admin是售前关联自己的客户的存储账号。
