### ISSUE TITLE
 在dashbaord 上创建bucket成功后需要手动刷新，才能看到bucket

### ISSUE THREAD

**Issue by breakwang** [bsc-s2/storage-dashboard-vue#18]
**描述是否是为了解决某个问题**
- 在dashbaord 上创建bucket，提示创建成功后，在页面上不能显示出该bucket，需要手动刷新才能显示

**描述期望的解决方法**
- 提示成功，就应该自动显示出来。
- 实在不行，提示用户手动刷新一下也行啊

**Comment by chenanyuan** [comment]
测试确实是这样。之前不会哈

**Comment by adwerrd** [comment]
了解 我修复下

**Comment by adwerrd** [comment]
#19 已经修复
