### ISSUE TITLE
删除bucket失败

### ISSUE THREAD

**Issue by breakwang** [bsc-s2/storage-dashboard-vue#22]
**问题描述**
控制台删除bucket失败，刷新下bucket还是会显示

**重现方法**
1. 打开`https://cwn-ss.portal.baishancloud.com/#/bucket`
2. 点击`我的存储`
3. 选择一个bucket，点击`删除bucket`， 此时bucket消失，点击刷新，bucket 又出现了

**期待的结果**
点击删除bucket, 不在显示该bucket，且不能读取bucket 下的key

**Comment by breakwang** [comment]
不是必现， 有个用户的bucket通过portal 删不掉，但是我自己测试的bucket可以删掉。

`user_kfzimg` 这个用户想在portal上删除`pmimg`和`kfz-shopimg` 这两个bucket，结果删不掉，我通过superadmin切换到该用户，验证了确实出现了删不掉的情况，然后我通过s2mgr 帮助用户删除了这两个bucket。

后来我切换到了自己的portal 上，尝试验证下删除bucket功能, 成功的删除了几个测试的bucket

**Comment by adwerrd** [comment]
这两个 bucket 跟其他 bucket 有什么区别么 ？

**Comment by adwerrd** [comment]
跟书文 确认过后发现问题出现在删除的逻辑上
bucket 删除操作会首先删除 bucket 下面所有的文件，如果文件过多，那么耗时会比较长，导致页面刷新时， bucket 依然没有删掉
目前前端由于缓存的问题，删除 bucket 后不会立刻刷新页面，而是在直接移除 bucket ，所以导致删除时 bucket 没了，但是刷新后又重新出现的问题
彻底解决这个问题需要在 **listBuckets** 接口上加一个字段，比如 正在删除中这种，标示出正在进行删除操作的 bucket
