### ISSUE TITLE
存储控制台页面时区问题导致数据错乱

### ISSUE THREAD

**Issue by piepiper** [bsc-s2/storage-dashboard-vue#25]
**描述是否是为了解决某个问题**
`https://cwn-ss.portal.baishancloud.com/`
`https://cwn-rrs.portal.baishancloud.com/`
等控制台页面展示的时候不是按东八区，数据会出现偏差，因为存储后台统计的时候，数据都是按照东八区算出来的。
例如用户从东2区，想要列出8月1号数据，web页面是按照用户的当地时间转换成unix time（北京时间 - 6 小时），取出来数据展示给用户，但是这样实际上取到了东八区7月31号的数据。是不对的。

**描述期望的解决方法**
咱们前端页面能做时区转换吗
需要把用户的时区强行转换到东八区时间，进行数据抓取并做页面展示。

**其他解决方法**

**Comment by adwerrd** [comment]
前端可以指定时区显示哈，根据毫秒数和时区来计算时间

**Comment by piepiper** [comment]
ok， 那就强制展示东八区时间即可

**Comment by adwerrd** [comment]
@piepiper 嗯嗯，这个需求在时间上有什么要求么

**Comment by piepiper** [comment]
不急，按照9月份做了处理即可吧

**Comment by adwerrd** [comment]
好 那我往后稍排一下哈，我争取周五上一下

**Comment by adwerrd** [comment]
#28  @piepiper 飞哥 我上线了一个修改 我本地不能复现 你看下你那边是不是正常哈

**Comment by piepiper** [comment]
fix #25
