### ISSUE TITLE
移除子账号 bucket acl 中 READ_ACP 权限的显示

### ISSUE THREAD

**Issue by adwerrd** [bsc-s2/storage-dashboard-vue#31]
**描述是否是为了解决某个问题**
READ_ACP 为默认权限，显示意义不大

**描述期望的解决方法**
不显示

**其他解决方法**

**Comment by adwerrd** [comment]
![image](https://user-images.githubusercontent.com/8522625/45804511-e715bd00-bcee-11e8-8a6f-74521ea9c1db.png)

**Comment by myy2829** [comment]
不显示是比较好的，我感觉前端来 过滤掉READ_ACP是比较好的吧，就像设置权限的时候，前端会默认添加READ_ACP.
感觉前后端的交互应该是用户真实的权限，至于展示与否，前端灵活控制吧。

**Comment by adwerrd** [comment]
好的
