### ISSUE TITLE
转码模板打开和创建特别慢（可以自己测试复现），且弹出不知道错误原因的错误见下图

### ISSUE THREAD

**Issue by chenanyuan** [bsc-s2/storage-dashboard-vue#43]
![image](https://user-images.githubusercontent.com/24269916/47265400-0c9a1e80-d55a-11e8-9f1e-690c60500e35.png)

**Comment by adwerrd** [comment]
我现在打开速度没发现慢，可能是 api 有抖动， 报错这个问题可能跟你选择的项目有关，你有时间帮我复现下哈

**Comment by ronghaoZHI** [comment]
@chenanyuan  这个没问题了 就先关了哈
