### ISSUE TITLE
仍然有用户 通过 console.bscstorage.com 登录

### ISSUE THREAD

**Issue by adwerrd** [bsc-s2/storage-dashboard-vue#49]
**问题描述**
仍然有用户 通过 console.bscstorage.com 登录，由于 sso 只允许 ss 系列域名登录，造成登录失败

**期待的结果**
@piepiper 飞哥能不能 由 console.bscstorage.com cname 到 ss.bscstorage.com
或者 前端提示跳转（ 会造成二次加载

**截屏**

![image](https://user-images.githubusercontent.com/8522625/47403892-cc1aea80-d77d-11e8-857c-def353b686ce.png)

**Comment by piepiper** [comment]
console.bscstorage.com 域名已下线
