### ISSUE TITLE
拖拽上传不能直接设置为public read

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/storage-dashboard-vue#9]
之前 @wenbobuaa  提到的1个, 用户使用不太方便的地方.

拖拽文件到浏览器中进行上传的时候, 没有一个配置上传文件的权限的机会. 只能上传后再调整.

具体情况如果描述不清楚 求文博补充哈.

@chenanyuan @adwerrd 看看产品和技术上是否可以帮这类用户解决这个问题.

**Comment by chenanyuan** [comment]
在上传文件的时候指定文件的 ACL ，这个方法应该可以

**Comment by chenanyuan** [comment]
![image](https://user-images.githubusercontent.com/24269916/43626458-7b270b5c-9724-11e8-9d8c-423fea32861d.png)

**Comment by chenanyuan** [comment]
![image](https://user-images.githubusercontent.com/24269916/43626577-0b73256a-9725-11e8-9515-c214e1083bcc.png)

**Comment by chenanyuan** [comment]
这个是产品上考虑的缺陷，谢谢提醒

**Comment by adwerrd** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property
前端可以支持哈
